### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by TheRusskiy** [stripe/terminal-js#20]
This is a weird question, but is there a way to use the Stripe JS SDK inside react-native?
Any technical limitations why react-native would need to use iOS/Android SDK's instead of this one?

**Comment by jdivock-stripe** [comment]
Hey @TheRusskiy thanks for the inquiry, react native is not currently supported with the JS SDK and we do strongly suggest if you go the react-native route to interop with the native iOS/Android SDKs. Our list of supported browsers is listed at https://stripe.com/docs/terminal/sdk/js#supported-browsers, but we'll be adding explicit guidance surrounding using our android/ios SDKs when using react native.

The limitations are less technical and more that we cannot guarantee stability in this integration shape as we can via the native android/iOS libraries.

**Comment by TheRusskiy** [comment]
thannk you @jdivock-stripe
