### ISSUE TITLE
discoverReaders() returns empty list

### ISSUE THREAD

**Issue by mahmoudsaeed** [stripe/terminal-js#52]
### Summary
`terminal.discoverReaders()` always returns an empty list. Upon further debugging, I figured out that the value of one of the query parameters is causing the issue.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/70577513/184218450-860e31e0-1874-4b51-81ad-39b60e6a610b.png">

Any value for `compatibile_sdk_version` that contains a PATCH number (the third one) makes the API to return an empty `data` array. It appears that the SDK sends version `1.3.2` to the API which does not work as mentioned.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/70577513/184219284-f31e2a1a-b8df-4cb6-acb4-d89a8f900fec.png">

If you use a different version number such as `1.3`, you will get the complete list of readers.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/70577513/184219520-d26d577e-9f57-459b-a05a-81eb670ae88e.png">

To reproduce the bug:
1. Create a connection token.
2. Initialize the SDK.
3. Discover readers (with `simulated: false`):
```
const config = {simulated: false};
const discoverResult = await terminal.discoverReaders(config);
if (discoverResult.error) {
  console.log('Failed to discover: ', discoverResult.error);
} else {
  console.log(discoverResult.discoveredReaders);  // Bug: always empty
}
```

**Comment by jdivock-stripe** [comment]
Hey @mahmoudsaeed thanks for the feedback, that reader being returning the `simulated_wisepos_e` is not intended to be used with the JS SDK and will only show up for our api based integrations. If you order and register hardware to your account you will see it returned in the list when simulated is false.
