### ISSUE TITLE
I can't cancel payment method retrieval with cancelCollectPaymentMethod after calling collectPaymentMethod

### ISSUE THREAD

**Issue by jsaunie** [stripe/terminal-js#53]
### Summary

Version : `@stripe/terminal-js@^0.10.1`
Reader: WisePOS E (Version 2.6.2.0)
Browser : Google chrome

I created a payment intent and ran "fetch payment method" with the client's secret token.
![Capture d’écran 2022-08-19 à 17 24 16](https://user-images.githubusercontent.com/29432650/185652864-b18f3341-be63-4ae1-bd1a-57c2c292bc67.png)

At this time, before inserting the card I want to cancel but the cancellation throws me this error.
```Invalid state: `cancelCollectPaymentMethod()` cancels an active attempt to get a payment method from a customer. However, there was no active attempt.```
![Capture d’écran 2022-08-19 à 17 20 43](https://user-images.githubusercontent.com/29432650/185652060-ea9d8a53-5764-4c38-abaf-6b112a9cf57e.png)

I checked several times, I get the payment method. I can't figure out how to set an active attempt so that I can cancel it. There is no information in the package or documentation.

**Comment by jdivock-stripe** [comment]
Hey @jsaunie, that call is meant to be invoked when the paired reader is in a collecting state. All our relevant docs, code snippets, and example implementations are linked out in the readme https://github.com/stripe/terminal-js#terminal-js-sdk-documentation

Please reference those docs for further guidance, thanks!
